from tk_builder.widgets.widget_wrappers.button import Button
from tk_builder.widgets.widget_wrappers.canvas import Canvas
from tk_builder.widgets.widget_wrappers.combobox import Combobox
from tk_builder.widgets.widget_wrappers.scale import Scale
from tk_builder.widgets.widget_wrappers.label import Label
from tk_builder.widgets.widget_wrappers.labelFrame import LabelFrame
from tk_builder.widgets.widget_wrappers.entry import Entry
from tk_builder.widgets.widget_wrappers.text import Text
from tk_builder.widgets.widget_wrappers.spinbox import Spinbox
from tk_builder.widgets.widget_wrappers.radiobutton import RadioButton
from tk_builder.widgets.widget_wrappers.checkbutton import CheckButton
from tk_builder.widgets.widget_wrappers.frame import Frame
from tk_builder.widgets.widget_wrappers.treeview import Treeview